name: Linting

on: [push, pull_request]

jobs:
  build_and_test:
    name: Linting and Typechecking
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Create .env file
        run: cp .env.example .env

      - name: NPM install
        run: npm install

      - name: Linting
        run: npm run lint

      - name: Typechecking
        run: npm run check
